default: watch

type-check:
    pnpm exec tsc --noEmit

build: type-check
    pnpm build

start:
    nakama migrate up --database.address postgres:localdb@localhost:5432
    nakama --runtime.js_entrypoint ./index.js --database.address postgres:localdb@localhost:5432 --logger.level DEBUG

watch:
    watchexec -r -e ts -- just build

deploy:
    cat .env | fly secrets import --stage
    fly deploy
